# Generated by Django 5.2.1 on 2025-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
