# Generated by Django 5.2.1 on 2025-06-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_answer_edit_date_alter_answer_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='edit_date',
        ),
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AnswerEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_text', models.TextField()),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='exams.answer')),
            ],
        ),
    ]
